apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      name: weather
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: weather:2.1.6.RELEASE
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: weather
  type: LoadBalancer