version: '3'
services:
  weather:
    image: "weather:2.1.6.RELEASE"
    ports:
      - "8081:8081"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  prediction:
    image: "prediction:2.1.6.LOCAL"
    ports:
      - "8082:8082"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  rbc:
    image: "rbc:2.1.6.RELEASE"
    ports:
      - "8083:8083"
    depends_on:
      - dbpostgresql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  hello:
    image: "hello:2.1.6.RELEASE"
    ports:
      - "8084:8084"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - dbpostgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./hello/env/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    env_file:
      - ./hello/env/grafana.env
    networks:
      vpcbr:
        ipv4_address: 10.5.0.12
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
