version: '3'
services:
  rbc:
    image: "rbc:2.1.6.RELEASE"
    ports:
      - "8083:8083"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - dbpostgresql
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    networks:
      vpcbr:
        ipv4_address: 10.5.0.10

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
